# Generated by Django 3.0.5 on 2020-04-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='types',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
